app:
    resource: "@AppBundle/Controller/"
    type:     annotation

addProduct:
    path:     /addProduct
    defaults: { _controller: AppBundle:Default:addProduct }

list_product:
    path:     /listProduct
    defaults: { _controller: AppBundle:Default:index }

ajax_order:
    path:     /ajax_order
    defaults: { _controller: AppBundle:Default:order }



